// South Indian Destinations Seed Data
// Rich, detailed data featuring Kerala and other South Indian states
// All prices in Indian Rupees (₹)

const destinations = [
  // =============== KERALA ===============
  {
    name: "Alleppey Backwaters",
    location: "Alappuzha, Kerala",
    state: "Kerala",
    description: "Experience the enchanting backwaters of Alleppey, often called the 'Venice of the East'. Cruise through serene canals lined with swaying coconut palms aboard a traditional houseboat (kettuvallam). Watch the golden sun melt into paddy fields, enjoy fresh Karimeen (Pearl Spot fish) prepared by your on-board chef, and drift into a world untouched by time. The intricate network of lagoons, lakes, and rivers stretching over 900 km will leave you mesmerized.",
    shortDescription: "Cruise the Venice of the East aboard traditional houseboats through palm-fringed canals.",
    images: [
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800",
      "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=800",
      "https://images.unsplash.com/photo-1609340747912-790370d8be55?w=800"
    ],
    price: 8999,
    originalPrice: 12999,
    category: "Backwaters",
    duration: "2 Days / 1 Night",
    rating: 4.8,
    totalReviews: 324,
    highlights: ["Houseboat cruise", "Kerala cuisine", "Village tours", "Sunrise views", "Coir making demos"],
    included: ["Houseboat stay", "All meals", "Guide", "Airport transfer"],
    coordinates: { lat: 9.4981, lng: 76.3388 },
    featured: true,
    bestTimeToVisit: "September to March",
    maxGroupSize: 8
  },
  {
    name: "Munnar Tea Gardens",
    location: "Munnar, Kerala",
    state: "Kerala",
    description: "Nestled at 1,600 metres in the Western Ghats, Munnar is a dreamy hill station carpeted with endless tea plantations. Walk through emerald-green tea estates as mist curls around the hills, visit the Tea Museum to learn about the region's colonial past, and spot the endangered Nilgiri Tahr at Eravikulam National Park. Munnar's cool climate, waterfalls, and rolling landscapes make it the perfect escape from tropical heat.",
    shortDescription: "Wander through misty tea plantations in Kerala's most stunning hill station.",
    images: [
      "https://images.unsplash.com/photo-1595815771614-ade9d652a65d?w=800",
      "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800",
      "https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=800"
    ],
    price: 7499,
    originalPrice: 10999,
    category: "Hill Station",
    duration: "3 Days / 2 Nights",
    rating: 4.7,
    totalReviews: 456,
    highlights: ["Tea estate walks", "Eravikulam National Park", "Mattupetty Dam", "Top Station viewpoint", "Tea Museum"],
    included: ["Hotel stay", "Breakfast", "Sightseeing", "Guide"],
    coordinates: { lat: 10.0889, lng: 77.0595 },
    featured: true,
    bestTimeToVisit: "September to May",
    maxGroupSize: 12
  },
  {
    name: "Fort Kochi Heritage Walk",
    location: "Kochi, Kerala",
    state: "Kerala",
    description: "Step into a living museum where Portuguese, Dutch, British, and Chinese influences blend seamlessly with Kerala's own rich culture. Explore the iconic Chinese fishing nets at sunset, visit the 16th-century St. Francis Church (India's oldest European church), wander through art galleries in the warehouse district, and watch a captivating Kathakali performance under lantern light. Fort Kochi's charming lanes, vibrant street art, and colonial architecture tell stories of centuries of maritime trade.",
    shortDescription: "Explore centuries of colonial history where East meets West in charming Fort Kochi.",
    images: [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800",
      "https://images.unsplash.com/photo-1580974928064-f0aeef70895a?w=800",
      "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800"
    ],
    price: 4999,
    originalPrice: 7499,
    category: "Heritage",
    duration: "2 Days / 1 Night",
    rating: 4.6,
    totalReviews: 278,
    highlights: ["Chinese fishing nets", "St. Francis Church", "Kathakali show", "Spice markets", "Street art tour"],
    included: ["Hotel stay", "Walking tour guide", "Kathakali show ticket", "Breakfast"],
    coordinates: { lat: 9.9658, lng: 76.2421 },
    featured: true,
    bestTimeToVisit: "October to February",
    maxGroupSize: 15
  },
  {
    name: "Wayanad Wildlife Safari",
    location: "Wayanad, Kerala",
    state: "Kerala",
    description: "Wayanad, cradled in the Western Ghats, is a biodiversity hotspot teeming with ancient forests, tribal heritage, and wildlife. Trek through bamboo groves to reach Chembra Peak's heart-shaped lake, explore the prehistoric Edakkal Caves with their 3,000-year-old petroglyphs, and spot elephants, langurs, and Malabar giant squirrels at Wayanad Wildlife Sanctuary. The lush spice plantations and misty mountain trails make every moment an adventure.",
    shortDescription: "Discover ancient caves, wildlife sanctuaries, and misty peaks in Kerala's green paradise.",
    images: [
      "https://images.unsplash.com/photo-1616091093714-c64882e9ecf4?w=800",
      "https://images.unsplash.com/photo-1570786686498-b6540db4fba5?w=800",
      "https://images.unsplash.com/photo-1592385391225-e0ed14d88979?w=800"
    ],
    price: 9499,
    originalPrice: 13999,
    category: "Wildlife",
    duration: "3 Days / 2 Nights",
    rating: 4.5,
    totalReviews: 189,
    highlights: ["Wildlife safari", "Edakkal Caves", "Chembra Peak trek", "Bamboo rafting", "Tribal village visit"],
    included: ["Resort stay", "All meals", "Safari permit", "Guide", "Trekking gear"],
    coordinates: { lat: 11.6854, lng: 76.1320 },
    featured: true,
    bestTimeToVisit: "October to May",
    maxGroupSize: 10
  },
  {
    name: "Varkala Cliff Beach",
    location: "Varkala, Kerala",
    state: "Kerala",
    description: "Varkala's dramatic red laterite cliffs plunge straight into the Arabian Sea, creating one of India's most spectacular beach settings. Below the cliff, pristine golden sand stretches along the shore, perfect for sunbathing and swimming. The 2,000-year-old Janardhana Swamy Temple perched atop adds spiritual depth. Enjoy Ayurvedic massages, fresh seafood at cliffside cafés, and stunning sunsets that paint the sky in shades of amber and crimson.",
    shortDescription: "Relax on golden sands beneath dramatic red cliffs overlooking the Arabian Sea.",
    images: [
      "https://images.unsplash.com/photo-1590766740554-e0e1d0c73f2b?w=800",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800"
    ],
    price: 5999,
    originalPrice: 8499,
    category: "Beach",
    duration: "3 Days / 2 Nights",
    rating: 4.4,
    totalReviews: 231,
    highlights: ["Cliff beach", "Ayurvedic spa", "Janardhana Temple", "Sunset watching", "Paragliding"],
    included: ["Beach resort stay", "Breakfast", "Ayurvedic massage", "Airport pickup"],
    coordinates: { lat: 8.7379, lng: 76.7163 },
    featured: false,
    bestTimeToVisit: "October to March",
    maxGroupSize: 12
  },
  {
    name: "Thekkady Periyar Tiger Reserve",
    location: "Thekkady, Kerala",
    state: "Kerala",
    description: "Periyar Tiger Reserve in Thekkady is one of India's finest wildlife sanctuaries, set around the stunning Periyar Lake. Take a boat safari to spot wild elephants drinking at the water's edge, go bamboo rafting through dense forests, and explore the spice plantations that fill the air with the scent of cardamom, pepper, and cinnamon. The Mangala Devi Temple, accessible only one day a year, and the border-area check dams add to the mystique.",
    shortDescription: "Spot elephants and tigers around the serene Periyar Lake in Kerala's premier wildlife reserve.",
    images: [
      "https://images.unsplash.com/photo-1474511320723-9a56873571b7?w=800",
      "https://images.unsplash.com/photo-1581852017103-68ac65514cf7?w=800",
      "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800"
    ],
    price: 8499,
    originalPrice: 11999,
    category: "Wildlife",
    duration: "3 Days / 2 Nights",
    rating: 4.6,
    totalReviews: 198,
    highlights: ["Boat safari on Periyar Lake", "Spice plantation tour", "Bamboo rafting", "Night patrol", "Tribal heritage tour"],
    included: ["Treehouse/resort stay", "All meals", "Safari permits", "Spice tour", "Guide"],
    coordinates: { lat: 9.6000, lng: 77.1667 },
    featured: false,
    bestTimeToVisit: "September to April",
    maxGroupSize: 10
  },
  {
    name: "Kovalam Beach Paradise",
    location: "Kovalam, Kerala",
    state: "Kerala",
    description: "Kovalam's crescent-shaped coastline, marked by the iconic Vizhinjam Lighthouse, has been a favourite beach destination since the 1930s when it was discovered by European travellers. The three adjoining beaches — Lighthouse Beach, Hawah Beach, and Samudra Beach — offer everything from surfing and parasailing to tranquil Ayurvedic retreats. The fishing village backdrop, fresh catch-of-the-day restaurants, and proximity to Thiruvananthapuram make Kovalam an accessible tropical paradise.",
    shortDescription: "Three stunning crescent beaches with Ayurvedic wellness, surfing, and lighthouse views.",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
      "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800",
      "https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=800"
    ],
    price: 6499,
    originalPrice: 9499,
    category: "Beach",
    duration: "3 Days / 2 Nights",
    rating: 4.3,
    totalReviews: 312,
    highlights: ["Lighthouse views", "Surfing lessons", "Ayurvedic spa", "Fishing village", "Sunset cruise"],
    included: ["Beach resort", "Breakfast & dinner", "Surfing lesson", "Lighthouse visit"],
    coordinates: { lat: 8.3988, lng: 76.9790 },
    featured: false,
    bestTimeToVisit: "September to March",
    maxGroupSize: 15
  },
  {
    name: "Athirappilly Waterfalls",
    location: "Thrissur, Kerala",
    state: "Kerala",
    description: "Known as the 'Niagara of India', Athirappilly Falls cascades 80 feet through lush tropical forests of the Sholayar range. The thundering waters surrounded by dense biodiversity — home to the Great Indian Hornbill, Lion-tailed Macaque, and over 200 species of birds — create a spectacle like no other in South India. The nearby Vazhachal Falls and Charpa Falls complete a waterfall circuit that is nothing short of magical, especially during the monsoon season.",
    shortDescription: "Witness the 'Niagara of India' cascading through ancient tropical forests.",
    images: [
      "https://images.unsplash.com/photo-1494472155656-f34e81b17ddc?w=800",
      "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800",
      "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800"
    ],
    price: 3999,
    originalPrice: 5999,
    category: "Waterfall",
    duration: "1 Day",
    rating: 4.5,
    totalReviews: 445,
    highlights: ["Athirappilly Falls", "Vazhachal Falls", "Rainforest trek", "Bird watching", "Tribal museum"],
    included: ["Transport", "Entry tickets", "Guide", "Lunch"],
    coordinates: { lat: 10.2855, lng: 76.5698 },
    featured: true,
    bestTimeToVisit: "June to January",
    maxGroupSize: 20
  },
  {
    name: "Kumarakom Bird Sanctuary",
    location: "Kumarakom, Kerala",
    state: "Kerala",
    description: "Spread across 14 acres on the banks of Vembanad Lake, Kumarakom Bird Sanctuary is a paradise for birdwatchers. Home to migratory birds like Siberian cranes, egrets, darters, and herons, the sanctuary comes alive at dawn and dusk. Stay in a luxurious lakeside resort, take a canoe ride through the mangroves, and enjoy Kerala's legendary hospitality. The tranquil Vembanad Lake — the longest lake in India — provides a breathtaking backdrop.",
    shortDescription: "A birdwatcher's dream on the shores of Vembanad Lake with luxury lakeside stays.",
    images: [
      "https://images.unsplash.com/photo-1549366021-9f761d450615?w=800",
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800",
      "https://images.unsplash.com/photo-1504567961542-e24d9439a724?w=800"
    ],
    price: 7999,
    originalPrice: 10999,
    category: "Wildlife",
    duration: "2 Days / 1 Night",
    rating: 4.4,
    totalReviews: 167,
    highlights: ["Bird watching", "Canoe ride", "Vembanad Lake sunset", "Ayurvedic spa", "Kerala Sadya feast"],
    included: ["Lakeside resort", "All meals", "Bird tour guide", "Canoe ride"],
    coordinates: { lat: 9.5916, lng: 76.4314 },
    featured: false,
    bestTimeToVisit: "November to February",
    maxGroupSize: 10
  },
  {
    name: "Bekal Fort & Beach",
    location: "Kasaragod, Kerala",
    state: "Kerala",
    description: "The largest and best-preserved fort in Kerala, Bekal Fort rises majestically above the Arabian Sea, offering panoramic views of the coastline. Built in 1650 AD, the fort's circular structure, underground passages, and observation towers tell tales of the Kadamba dynasty. The pristine Bekal Beach below, with its shallow waters and backdrop of Pallikere Beach, provides the perfect setting for a serene South Indian coastal experience.",
    shortDescription: "Kerala's largest fort overlooking pristine beaches and the vast Arabian Sea.",
    images: [
      "https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=800",
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800",
      "https://images.unsplash.com/photo-1559827291-bce6e0040bfd?w=800"
    ],
    price: 5499,
    originalPrice: 7999,
    category: "Heritage",
    duration: "2 Days / 1 Night",
    rating: 4.3,
    totalReviews: 142,
    highlights: ["Fort exploration", "Beach walk", "Ananthapura Temple", "Chandragiri Fort", "Theyyam performance"],
    included: ["Resort stay", "Breakfast", "Fort guide", "Entry tickets"],
    coordinates: { lat: 12.3927, lng: 75.0327 },
    featured: false,
    bestTimeToVisit: "October to February",
    maxGroupSize: 15
  },

  // =============== TAMIL NADU ===============
  {
    name: "Meenakshi Temple, Madurai",
    location: "Madurai, Tamil Nadu",
    state: "Tamil Nadu",
    description: "The Meenakshi Amman Temple is a masterpiece of Dravidian architecture, with 14 towering gopurams (gateway towers) covered in 33,000 colourful sculptures of gods, demons, and mythical creatures. This 2,500-year-old temple complex dedicated to Goddess Meenakshi and Lord Sundareswarar is a living, breathing centre of Tamil culture. The evening ceremony where Lord Sundareswarar is ceremonially taken to Meenakshi's chamber is a deeply moving spiritual experience.",
    shortDescription: "Marvel at 33,000 colourful sculptures in one of India's grandest Dravidian temples.",
    images: [
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800",
      "https://images.unsplash.com/photo-1621427645698-7c8ad6a5f89c?w=800",
      "https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800"
    ],
    price: 5499,
    originalPrice: 7999,
    category: "Temple",
    duration: "2 Days / 1 Night",
    rating: 4.8,
    totalReviews: 567,
    highlights: ["Gopuram tour", "Evening ceremony", "Temple museum", "Banana leaf meal", "Thirumalai Nayak Palace"],
    included: ["Hotel stay", "Temple guide", "Traditional lunch", "Palace entry"],
    coordinates: { lat: 9.9195, lng: 78.1193 },
    featured: true,
    bestTimeToVisit: "October to March",
    maxGroupSize: 20
  },
  {
    name: "Ooty - Queen of Hill Stations",
    location: "Nilgiris, Tamil Nadu",
    state: "Tamil Nadu",
    description: "Ooty, the Queen of the Nilgiris, is a colonial-era hill station wrapped in eucalyptus-scented mist at 2,240 metres. Ride the UNESCO World Heritage Nilgiri Mountain Railway as it chugs through 16 tunnels and over 250 bridges. Wander through the stunning Botanical Gardens established in 1848, take a boat ride on Ooty Lake, and sip fresh Nilgiri tea overlooking rolling green hills. The Toda tribal hamlets and Doddabetta Peak add cultural and natural depth.",
    shortDescription: "Ride the heritage toy train through misty Nilgiri Mountains and colonial charm.",
    images: [
      "https://images.unsplash.com/photo-1605722625421-21b8e4a7a0d8?w=800",
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800",
      "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800"
    ],
    price: 6999,
    originalPrice: 9999,
    category: "Hill Station",
    duration: "3 Days / 2 Nights",
    rating: 4.5,
    totalReviews: 389,
    highlights: ["Nilgiri Mountain Railway", "Botanical Gardens", "Ooty Lake", "Doddabetta Peak", "Tea factory visit"],
    included: ["Hotel stay", "Toy train ticket", "Breakfast", "Sightseeing"],
    coordinates: { lat: 11.4102, lng: 76.6950 },
    featured: true,
    bestTimeToVisit: "March to June, September to November",
    maxGroupSize: 15
  },
  {
    name: "Mahabalipuram Shore Temple",
    location: "Mahabalipuram, Tamil Nadu",
    state: "Tamil Nadu",
    description: "A UNESCO World Heritage Site, Mahabalipuram's Shore Temple stands as one of the oldest structural stone temples in South India, built by the Pallava kings in the 7th century. The Five Rathas (monolithic rock-cut temples), Arjuna's Penance (the world's largest open-air bas-relief), and the iconic shore temple silhouetted against crashing waves make this an unrivalled cultural experience. The town's living tradition of stone carving continues to this day.",
    shortDescription: "7th-century UNESCO rock temples where ancient Pallava art meets the Bay of Bengal.",
    images: [
      "https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?w=800",
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800",
      "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800"
    ],
    price: 3999,
    originalPrice: 5999,
    category: "Heritage",
    duration: "1 Day",
    rating: 4.6,
    totalReviews: 298,
    highlights: ["Shore Temple", "Five Rathas", "Arjuna's Penance", "Stone carving workshops", "Beach sunset"],
    included: ["Transport from Chennai", "Entry tickets", "Guide", "Lunch"],
    coordinates: { lat: 12.6172, lng: 80.1999 },
    featured: false,
    bestTimeToVisit: "November to February",
    maxGroupSize: 20
  },
  {
    name: "Kodaikanal - Princess of Hills",
    location: "Kodaikanal, Tamil Nadu",
    state: "Tamil Nadu",
    description: "Kodaikanal, the 'Princess of Hill Stations', sits at 2,133 metres amidst dense forests of pine and eucalyptus. The star-shaped lake at the town's heart, the misty trails of Coaker's Walk, and the thundering waterfalls of Silver Cascade create a romantic atmosphere. Visit the curious Pillar Rocks, cycle around the lake, and explore the 12-acre Bryant Park. The Kurinji flower, which blooms once every 12 years, carpets these hills in blue — an event that draws visitors worldwide.",
    shortDescription: "A romantic hill station with a star-shaped lake, misty trails, and pine forests.",
    images: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800",
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800"
    ],
    price: 6499,
    originalPrice: 8999,
    category: "Hill Station",
    duration: "3 Days / 2 Nights",
    rating: 4.4,
    totalReviews: 267,
    highlights: ["Kodaikanal Lake", "Coaker's Walk", "Silver Cascade", "Pillar Rocks", "Bryant Park"],
    included: ["Hotel stay", "Breakfast", "Sightseeing", "Boat ride"],
    coordinates: { lat: 10.2381, lng: 77.4892 },
    featured: false,
    bestTimeToVisit: "March to May, September to November",
    maxGroupSize: 12
  },
  {
    name: "Rameswaram Temple Island",
    location: "Rameswaram, Tamil Nadu",
    state: "Tamil Nadu",
    description: "Rameswaram, one of the four sacred Char Dham pilgrimage sites, sits on Pamban Island connected to the mainland by India's first sea bridge. The Ramanathaswamy Temple boasts the longest temple corridor in the world (1,220 metres) with over 1,200 granite pillars. Bathe in the 22 sacred theerthams within the temple, walk across the dramatic Pamban Bridge, and visit the Ghost Town of Dhanushkodi — destroyed by a cyclone in 1964 and now hauntingly beautiful.",
    shortDescription: "Sacred island temple with the world's longest corridor and the dramatic Pamban Bridge.",
    images: [
      "https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800",
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800",
      "https://images.unsplash.com/photo-1512100356356-de1b84283e18?w=800"
    ],
    price: 4999,
    originalPrice: 6999,
    category: "Temple",
    duration: "2 Days / 1 Night",
    rating: 4.7,
    totalReviews: 412,
    highlights: ["Ramanathaswamy Temple", "Pamban Bridge", "Dhanushkodi", "22 Theerthams", "APJ Kalam Memorial"],
    included: ["Hotel stay", "Temple guide", "All transport", "Breakfast"],
    coordinates: { lat: 9.2876, lng: 79.3129 },
    featured: false,
    bestTimeToVisit: "October to April",
    maxGroupSize: 20
  },

  // =============== KARNATAKA ===============
  {
    name: "Hampi - Ruins of Vijayanagara",
    location: "Hampi, Karnataka",
    state: "Karnataka",
    description: "Hampi, the once-mighty capital of the Vijayanagara Empire, spreads across a surreal landscape of giant granite boulders and banana plantations along the Tungabhadra River. This UNESCO World Heritage Site houses over 500 ancient monuments — from the ornate Vittala Temple with its musical pillars to the massive Virupaksha Temple still active after 700 years. Rent a bicycle, explore royal enclosures, watch sunset from Matanga Hill, and experience history on an epic scale.",
    shortDescription: "UNESCO ruins of a mighty empire set among surreal boulder-strewn landscapes.",
    images: [
      "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800",
      "https://images.unsplash.com/photo-1600100397608-e1f61e7e3cee?w=800",
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800"
    ],
    price: 5999,
    originalPrice: 8999,
    category: "Heritage",
    duration: "3 Days / 2 Nights",
    rating: 4.7,
    totalReviews: 423,
    highlights: ["Vittala Temple", "Stone Chariot", "Matanga Hill sunset", "Coracle ride", "Virupaksha Temple"],
    included: ["Guesthouse stay", "Breakfast", "Bicycle rental", "Guide", "Entry tickets"],
    coordinates: { lat: 15.3350, lng: 76.4600 },
    featured: true,
    bestTimeToVisit: "October to February",
    maxGroupSize: 15
  },
  {
    name: "Coorg Coffee Country",
    location: "Coorg (Kodagu), Karnataka",
    state: "Karnataka",
    description: "Coorg, the 'Scotland of India', is a misty hill district draped in coffee and spice plantations. Home to the warrior Kodava community, Coorg offers a unique blend of natural beauty and martial culture. Trek to Tadiandamol Peak (Karnataka's highest peak), visit the Dubare Elephant Camp to bathe elephants in the Kaveri River, and taste some of India's finest Robusta coffee straight from the estate. Abbey Falls and Raja's Seat offer postcard-perfect views.",
    shortDescription: "Misty coffee plantations, elephant encounters, and warrior heritage in Karnataka's hills.",
    images: [
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800",
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800",
      "https://images.unsplash.com/photo-1432405972618-c60b0225b8f9?w=800"
    ],
    price: 7999,
    originalPrice: 11499,
    category: "Hill Station",
    duration: "3 Days / 2 Nights",
    rating: 4.6,
    totalReviews: 334,
    highlights: ["Coffee estate stay", "Dubare Elephant Camp", "Abbey Falls", "Raja's Seat", "Tadiandamol trek"],
    included: ["Plantation stay", "All meals", "Coffee tasting", "Elephant camp", "Guide"],
    coordinates: { lat: 12.4244, lng: 75.7382 },
    featured: true,
    bestTimeToVisit: "October to March",
    maxGroupSize: 12
  },
  {
    name: "Mysore Palace & Heritage",
    location: "Mysuru, Karnataka",
    state: "Karnataka",
    description: "Mysuru, the cultural capital of Karnataka, revolves around the magnificent Mysore Palace — one of India's most visited monuments. The Indo-Saracenic palace, illuminated by 97,000 light bulbs every Sunday evening, is a feast for the eyes. Explore the vibrant Devaraja Market for silk saris and sandalwood, climb Chamundi Hills to the ancient Chamundeshwari Temple, and visit the stunning Brindavan Gardens with its musical fountain show.",
    shortDescription: "India's most illuminated palace city with silk, sandalwood, and royal grandeur.",
    images: [
      "https://images.unsplash.com/photo-1600100397608-e1f61e7e3cee?w=800",
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800",
      "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800"
    ],
    price: 5499,
    originalPrice: 7999,
    category: "Heritage",
    duration: "2 Days / 1 Night",
    rating: 4.5,
    totalReviews: 378,
    highlights: ["Mysore Palace illumination", "Chamundi Hills", "Devaraja Market", "Brindavan Gardens", "Silk factory tour"],
    included: ["Heritage hotel stay", "Breakfast", "Palace entry", "Guide", "Market tour"],
    coordinates: { lat: 12.3051, lng: 76.6551 },
    featured: false,
    bestTimeToVisit: "October to February",
    maxGroupSize: 20
  },
  {
    name: "Gokarna Beach Trek",
    location: "Gokarna, Karnataka",
    state: "Karnataka",
    description: "Gokarna is the lesser-known sibling of Goa — quieter, more spiritual, and arguably more beautiful. Four stunning beaches — Kudle, Om, Half Moon, and Paradise — are connected by cliff trails perfect for trekking. The sacred Mahabaleshwar Temple adds a spiritual dimension, while beach shacks serving fresh seafood and live music under the stars create unforgettable evenings. Om Beach, shaped naturally like the sacred symbol, is truly unique.",
    shortDescription: "Trek between hidden beaches shaped like sacred symbols in Karnataka's coastal gem.",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800",
      "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800"
    ],
    price: 4999,
    originalPrice: 6999,
    category: "Beach",
    duration: "3 Days / 2 Nights",
    rating: 4.5,
    totalReviews: 256,
    highlights: ["Beach trek", "Om Beach", "Paradise Beach", "Mahabaleshwar Temple", "Cliff camping"],
    included: ["Beach stay", "Breakfast", "Trek guide", "Snorkeling gear"],
    coordinates: { lat: 14.5479, lng: 74.3188 },
    featured: false,
    bestTimeToVisit: "October to March",
    maxGroupSize: 12
  },

  // =============== ANDHRA PRADESH ===============
  {
    name: "Tirupati Balaji Temple",
    location: "Tirupati, Andhra Pradesh",
    state: "Andhra Pradesh",
    description: "Tirumala Venkateswara Temple, perched atop the seven peaks of Tirumala Hills, is the world's richest and most visited temple. Over 50,000 devotees visit daily, drawn by the magnetic presence of Lord Venkateswara (Balaji). The darshan experience — through ornate corridors lined with gold — is profoundly moving. The temple's Laddu prasadam is world-famous. The surrounding Tirumala hills offer trekking trails, ancient inscriptions, and breathtaking views of the Eastern Ghats.",
    shortDescription: "The world's richest temple atop seven sacred hills with divine darshan experiences.",
    images: [
      "https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800",
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800",
      "https://images.unsplash.com/photo-1621427645698-7c8ad6a5f89c?w=800"
    ],
    price: 4499,
    originalPrice: 6499,
    category: "Temple",
    duration: "2 Days / 1 Night",
    rating: 4.8,
    totalReviews: 689,
    highlights: ["Special darshan", "Laddu prasadam", "Tirumala trek", "Sri Padmavathi Temple", "TTD Museum"],
    included: ["Hotel stay", "Special darshan ticket", "Breakfast", "Transport to Tirumala"],
    coordinates: { lat: 13.6288, lng: 79.4192 },
    featured: true,
    bestTimeToVisit: "September to March",
    maxGroupSize: 20
  },
  {
    name: "Araku Valley & Borra Caves",
    location: "Visakhapatnam, Andhra Pradesh",
    state: "Andhra Pradesh",
    description: "Araku Valley, a hidden hill station in the Eastern Ghats, is home to indigenous tribal communities and stunning natural beauty. The journey itself — aboard the vintage Kirandur-Araku train through 46 tunnels and over 84 bridges — is an experience of a lifetime. Explore the million-year-old Borra Caves with their spectacular stalactite formations, taste Araku's award-winning coffee at tribal plantations, and immerse yourself in the unique Dhimsa dance of the local Adivasi communities.",
    shortDescription: "A scenic train ride through 46 tunnels to tribal coffee valleys and million-year-old caves.",
    images: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800",
      "https://images.unsplash.com/photo-1494472155656-f34e81b17ddc?w=800"
    ],
    price: 5999,
    originalPrice: 8499,
    category: "Adventure",
    duration: "3 Days / 2 Nights",
    rating: 4.4,
    totalReviews: 178,
    highlights: ["Scenic train ride", "Borra Caves", "Tribal village visit", "Coffee plantations", "Padmapuram Gardens"],
    included: ["Resort stay", "Train tickets", "All meals", "Cave entry", "Guide"],
    coordinates: { lat: 18.3273, lng: 82.8756 },
    featured: false,
    bestTimeToVisit: "October to March",
    maxGroupSize: 15
  },

  // =============== TELANGANA ===============
  {
    name: "Hyderabad Heritage & Food Trail",
    location: "Hyderabad, Telangana",
    state: "Telangana",
    description: "Hyderabad, the City of Pearls and Biryani, is a magnificent fusion of Mughal grandeur and modern tech-city energy. The iconic Charminar, Golconda Fort's sound and light show, and the sprawling Salar Jung Museum (one of three National Museums) form the heritage backbone. But no Hyderabad trip is complete without a food trail — from the legendary Paradise Biryani to Irani chai at Nimrah Café, haleem during Ramadan, and the double ka meetha that melts in your mouth.",
    shortDescription: "Pearl city where Mughal grandeur meets legendary Biryani and modern tech culture.",
    images: [
      "https://images.unsplash.com/photo-1600100397608-e1f61e7e3cee?w=800",
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800",
      "https://images.unsplash.com/photo-1590077428593-a55bb07c4665?w=800"
    ],
    price: 5999,
    originalPrice: 8499,
    category: "Culture",
    duration: "3 Days / 2 Nights",
    rating: 4.5,
    totalReviews: 345,
    highlights: ["Charminar", "Golconda Fort", "Food trail", "Pearl shopping", "Salar Jung Museum"],
    included: ["Heritage hotel", "Breakfast", "Food trail guide", "Entry tickets", "Transport"],
    coordinates: { lat: 17.3850, lng: 78.4867 },
    featured: true,
    bestTimeToVisit: "October to March",
    maxGroupSize: 15
  },

  // =============== PUDUCHERRY ===============
  {
    name: "Pondicherry French Quarter",
    location: "Puducherry",
    state: "Puducherry",
    description: "Pondicherry's French Quarter (Ville Blanche) is a pastel-coloured dream — mustard-yellow colonial buildings line cobblestoned streets named Rue Suffren and Rue Dumas. Start your day with croissants at Baker Street, cycle along the Rock Beach promenade, visit the serene Sri Aurobindo Ashram, and end at the futuristic Auroville — a universal township experiment. The underwater scuba diving at Temple Reef, Heritage Town walks, and Promenade Beach sunset are quintessentially Pondicherry.",
    shortDescription: "French colonial charm with pastel streets, croissants, ashrams, and scuba diving.",
    images: [
      "https://images.unsplash.com/photo-1580974928064-f0aeef70895a?w=800",
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800",
      "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?w=800"
    ],
    price: 5499,
    originalPrice: 7999,
    category: "Culture",
    duration: "3 Days / 2 Nights",
    rating: 4.6,
    totalReviews: 312,
    highlights: ["French Quarter walk", "Auroville", "Scuba diving", "Sri Aurobindo Ashram", "Rock Beach"],
    included: ["Heritage hotel", "Breakfast", "Bicycle", "Walking tour guide", "Scuba session"],
    coordinates: { lat: 11.9416, lng: 79.8083 },
    featured: true,
    bestTimeToVisit: "October to March",
    maxGroupSize: 12
  },

  // =============== GOA ===============
  {
    name: "North Goa Beach Explorer",
    location: "North Goa",
    state: "Goa",
    description: "North Goa is the quintessential tropical beach paradise — Baga, Calangute, Anjuna, and Vagator beaches offer a vibrant mix of water sports, flea markets, and legendary nightlife. Explore the UNESCO-listed Basilica of Bom Jesus housing St. Francis Xavier's remains, cruise the Mandovi River at sunset with live Goan folk music, and feast on fresh Goan fish curry rice at beachside shacks. The Saturday Night Market at Arpora is a sensory explosion of food, music, and shopping.",
    shortDescription: "Sun-kissed beaches, Portuguese heritage, fresh seafood, and vibrant nightlife in tropical Goa.",
    images: [
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800",
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=800"
    ],
    price: 8999,
    originalPrice: 13499,
    category: "Beach",
    duration: "4 Days / 3 Nights",
    rating: 4.4,
    totalReviews: 478,
    highlights: ["Beach hopping", "Water sports", "Basilica of Bom Jesus", "Mandovi cruise", "Saturday Night Market"],
    included: ["Beach resort", "Breakfast", "Water sport (1)", "Mandovi cruise", "Airport transfer"],
    coordinates: { lat: 15.5004, lng: 73.8386 },
    featured: false,
    bestTimeToVisit: "November to February",
    maxGroupSize: 15
  },

  // ============ MORE KERALA ============
  {
    name: "Vagamon Meadows",
    location: "Vagamon, Kerala",
    state: "Kerala",
    description: "Vagamon, one of Kerala's best-kept secrets, is a serene hill station with rolling meadows, pine forests, and misty valleys. Paragliding over the lush green landscape is the main adrenaline draw. Walk through the mystical pine forests of Vagamon, visit the chain of three hills — Thangal, Murugan, and Kurisumala — and experience the tranquility of the Vagamon Meadows. The annual Monsoon Music Festival adds cultural vibrancy to this pastoral paradise.",
    shortDescription: "Paraglide over rolling misty meadows in Kerala's tranquil hidden hill station.",
    images: [
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800",
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800"
    ],
    price: 5999,
    originalPrice: 8499,
    category: "Adventure",
    duration: "2 Days / 1 Night",
    rating: 4.3,
    totalReviews: 134,
    highlights: ["Paragliding", "Pine forest walks", "Meadow camping", "Kurisumala pilgrimage", "Rock climbing"],
    included: ["Resort stay", "Breakfast & dinner", "Paragliding session", "Guide"],
    coordinates: { lat: 9.6860, lng: 76.9041 },
    featured: false,
    bestTimeToVisit: "September to May",
    maxGroupSize: 10
  },
  {
    name: "Thrissur Pooram Experience",
    location: "Thrissur, Kerala",
    state: "Kerala",
    description: "Thrissur Pooram is the 'festival of all festivals' in Kerala — a grand spectacle of decorated elephants, panchavadyam (five-instrument ensemble), and the legendary Kudamattam (umbrella ceremony). Held annually at the Vadakkunnathan Temple, this cultural extravaganza features two rival temple processions competing in pomp and pageantry. The fireworks display at dawn is one of the largest in Asia. Experience Kerala's cultural soul in its most magnificent expression.",
    shortDescription: "Kerala's grandest temple festival with decorated elephants and Asia's largest fireworks.",
    images: [
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800",
      "https://images.unsplash.com/photo-1614082242765-7c98ca0f3df3?w=800",
      "https://images.unsplash.com/photo-1621427645698-7c8ad6a5f89c?w=800"
    ],
    price: 6999,
    originalPrice: 9999,
    category: "Culture",
    duration: "2 Days / 1 Night",
    rating: 4.9,
    totalReviews: 98,
    highlights: ["Elephant procession", "Kudamattam", "Fireworks display", "Vadakkunnathan Temple", "Traditional music"],
    included: ["Hotel stay", "VIP viewing area", "Guide", "Traditional meals"],
    coordinates: { lat: 10.5276, lng: 76.2144 },
    featured: false,
    bestTimeToVisit: "April - May (Pooram dates vary)",
    maxGroupSize: 20
  },
  {
    name: "Silent Valley National Park",
    location: "Palakkad, Kerala",
    state: "Kerala",
    description: "Silent Valley is one of the last undisturbed tracts of South Western Ghats mountain rainforest. Named for the absence of cicadas (hence the 'silence'), this pristine park shelters the endangered Lion-tailed Macaque, Nilgiri Langur, and over 1,000 species of flowering plants. The Kunti River meanders through the valley, and the virgin forests — estimated to be 50 million years old — represent one of the oldest ecosystems on Earth. Entry is strictly regulated to preserve its fragile ecology.",
    shortDescription: "One of Earth's oldest rainforests sheltering rare wildlife in total pristine silence.",
    images: [
      "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800",
      "https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800",
      "https://images.unsplash.com/photo-1549366021-9f761d450615?w=800"
    ],
    price: 4999,
    originalPrice: 6999,
    category: "Wildlife",
    duration: "2 Days / 1 Night",
    rating: 4.7,
    totalReviews: 89,
    highlights: ["Rainforest trek", "Lion-tailed Macaque spotting", "Kunti River walk", "Sairandhri viewpoint", "Tribal interaction"],
    included: ["Forest lodge", "All meals", "Permit", "Naturalist guide", "Jeep safari"],
    coordinates: { lat: 11.0803, lng: 76.4260 },
    featured: false,
    bestTimeToVisit: "December to April",
    maxGroupSize: 8
  }
];

module.exports = destinations;
